[package]
name = "tar-no-std"
description = "A no_std, allocation-free library focused on reading regular files from basic Tar archives"
version = "0.5.0"
edition = "2024"
keywords = ["tar", "tarball", "archive"]
categories = ["data-structures", "no-std", "parser-implementations"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/phip1611/tar-no-std"
repository = "https://github.com/phip1611/tar-no-std"
documentation = "https://docs.rs/tar-no-std"
rust-version = "1.85.0"
exclude = [
  "tests"
]

[features]
default = []
alloc = []

[[example]]
name = "alloc_feature"
required-features = ["alloc"]

[dependencies]
bitflags = "2.12"
log = { version = "~0.4", default-features = false }
num-traits =  { version = "~0.2", default-features = false }

[dev-dependencies]
env_logger = "0.11"

[package.metadata.docs.rs]
all-features = true
