[package]
name = "tar-no-std-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.tar-no-std]
path = ".."

[[bin]]
name = "parse_archive"
path = "fuzz_targets/parse_archive.rs"
test = false
doc = false
bench = false
