name: Build

on: [ push, pull_request, merge_group ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: "${{ matrix.runs-on }}"
    strategy:
      matrix:
        runs-on:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        rust:
          - stable
          - nightly
          - 1.85.0 # MSVR
    steps:
      - uses: actions/checkout@v7
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "${{ matrix.rust }}"
      - uses: Swatinem/rust-cache@v2
        with:
          key: "${{ matrix.runs-on }}-${{ matrix.rust }}"
      - name: Build
        run: cargo build --all-targets --verbose --features alloc
      # use some arbitrary no_std target
      - name: Install no_std target thumbv7em-none-eabihf
        run: rustup target add thumbv7em-none-eabihf
      - name: Build (no_std)
        run: cargo build --verbose --target thumbv7em-none-eabihf --features alloc
      - name: Run tests
        run: cargo test --verbose --features alloc

  fuzz:
    runs-on: ubuntu-latest
    needs:
      # Logical dependency
      - build
    strategy:
      matrix:
        rust:
          - nightly
    steps:
      - uses: actions/checkout@v7
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "${{ matrix.rust }}"
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            . -> target
            fuzz -> target
      - run: cargo install cargo-fuzz
      - name: Build fuzz targets
        run: cargo fuzz build
      - name: Fuzz all targets
        run: |
          # Target 1: We use existing tarballs as base line corpus.
          mkdir -p fuzz/corpus/parse_archive
          cargo fuzz run parse_archive fuzz/corpus/parse_archive tests -- -max_total_time=30

          # Target 2: Generates valid tarballs (initial header and checksom
          # are correct) dynamically.
          cargo +nightly fuzz run parse_valid_archive -- -max_total_time=30
      - name: Upload crash artifacts
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: fuzz-crash-${{ matrix.target }}
          path: fuzz/artifacts/${{ matrix.target }}/

  miri:
    runs-on: "${{ matrix.runs-on }}"
    needs:
      # Logical dependency and wait for cache to be present
      - build
    strategy:
      matrix:
        runs-on:
          - ubuntu-latest
        rust:
          - nightly
    steps:
      - uses: actions/checkout@v7
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "${{ matrix.rust }}"
      - uses: Swatinem/rust-cache@v2
        with:
          key: "${{ matrix.runs-on }}-${{ matrix.rust }}"
      - run: rustup component add miri
      - run: cargo miri test --tests

  style_checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - uses: actions/checkout@v7
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "${{ matrix.rust }}"
      - uses: Swatinem/rust-cache@v2
        with:
          key: "${{ matrix.runs-on }}-${{ matrix.rust }}"
      - name: Rustfmt
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --features alloc --all-targets
      - name: Rustdoc
        run: cargo doc --no-deps --document-private-items --features alloc
